// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using Cirrious.MvvmCross.Binding.Touch.Views;

namespace storyb
{
	public partial class StandardTableViewCell : MvxStandardTableViewCell
	{
		public StandardTableViewCell (IntPtr handle) 
			: base ("TitleText Name", handle)
		{
		}
	}
}
